name: Github actions test
on: [push]
jobs:
    run_example_job:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: wisedev.xyz
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: | 
            whoami